// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using core7_postgre_angular14.Helpers;

#nullable disable

namespace core7_postgre_angular14.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("core7_postgre_angular14.Entities.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<int>("alert_level")
                        .HasColumnType("integer")
                        .HasColumnName("alert_level");

                    b.Property<string>("category")
                        .HasColumnType("varchar")
                        .HasColumnName("category");

                    b.Property<decimal>("cost_price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cost_price");

                    b.Property<int>("critical_level")
                        .HasColumnType("integer")
                        .HasColumnName("critical_level");

                    b.Property<string>("descriptions")
                        .HasColumnType("varchar")
                        .HasColumnName("descriptions");

                    b.Property<string>("prod_pic")
                        .HasColumnType("varchar")
                        .HasColumnName("prod_pic");

                    b.Property<int>("qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<decimal>("sale_price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sale_price");

                    b.Property<decimal>("sell_price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("sell_price");

                    b.Property<string>("unit")
                        .HasColumnType("varchar")
                        .HasColumnName("unit");

                    b.HasKey("id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("core7_postgre_angular14.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar")
                        .HasColumnName("firstname");

                    b.Property<int>("Isactivated")
                        .HasColumnType("integer")
                        .HasColumnName("isactivated");

                    b.Property<int>("Isblocked")
                        .HasColumnType("integer")
                        .HasColumnName("isblocked");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar")
                        .HasColumnName("lastname");

                    b.Property<int>("Mailtoken")
                        .HasColumnType("integer")
                        .HasColumnName("mailtoken");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar")
                        .HasColumnName("mobile");

                    b.Property<string>("Password")
                        .HasColumnType("varchar")
                        .HasColumnName("password");

                    b.Property<string>("Profilepic")
                        .HasColumnType("varchar")
                        .HasColumnName("profilepic");

                    b.Property<string>("Qrcodeurl")
                        .HasColumnType("varchar")
                        .HasColumnName("qrcodeurl");

                    b.Property<string>("Roles")
                        .HasColumnType("varchar")
                        .HasColumnName("roles");

                    b.Property<string>("Secretkey")
                        .HasColumnType("text")
                        .HasColumnName("secretkey");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
